### ISSUE TITLE
How to boot Windows ISO

### ISSUE THREAD

**Issue by knuxyl** [nitanmarcel/isodrive-magisk#2]
Updated script 1/25/2025 to do some minor cleanup.
I read the Wiki and saying to create a 10gb partition is a little vague. You cant repartition android, so I'm not quite sure what this means.

I found a better solution though. The linux file gadget driver isn't included in Windows which is why it complains drivers are missing. It boots the live environment, but does not mount the actual installer sources to a letter because it doesn't load the driver.

The basic idea is to create a dummy USB image, install ventoy on it, and then copy the Windows iso over. I'm guessing loading the installer through Ventoy is like a virtual environment, so Windows doesn't communicate directly with the hardware/usb it is on.

Ventoy: https://github.com/ventoy/Ventoy

This is the bash script I wrote to do this in Linux

usage
sudo bash script.sh ISOFILE
```
#!/bin/bash
version="ventoy-1.1.00"
ventoy="${version}/Ventoy2Disk.sh"
if [ "$(whoami)" != "root" ]; then
	echo "Please run this as root or sudo"
	exit
fi
currentuser="${SUDO_USER}"
if [ "${currentuser}" == "" ]; then
	currentuser="root"
fi
if [ ! -f "${ventoy}" ]; then
	echo "${ventoy}"
	echo "Please update ventoy version in this script or move ventoy to"
	echo "${version}/"
	echo "Download ventoy here"
	echo "https://www.ventoy.net/en/download.html"
	exit
fi
if [[ "${1}" == "" ]]; then
	echo "Usage:"
	echo "bash createusb.sh IMAGEFILE"
	echo "IMAGEFILE = your source image file"
else
	count=0
	output="$(basename "${1%.*}").img"
	while [[ -f "${output}" ]]; do
		output="${output%.*}_${count}.img"
		count=$(("${count}" + 1))
	done
	imagename=$(file "${1}" | cut -f 2 -d "'" | tr [:lower:] [:upper:] | cut -c 1-12)
	imagefilename=$(basename ${output} | sed 's/_[0-9]\.//g' | sed 's/\.//g' | sed 's/-//g' | sed 's/_//g' | tr [:lower:] [:upper:] | cut -c 1-12)
	imagesize=$((($(ls -s "${1}" | cut -f 1 -d " ") / 1000) + 64))
	echo "Choose a partition label"
	echo "a) Blank"
	echo "b) ${imagename}"
	echo "c) ${imagefilename}"
	read -p "Enter selection [A/b/c] " p
	if [[ "${p}" =~ ^[bB]$ ]]; then
		label="${imagename}"
	elif [[ "${p}" =~ ^[cC]$ ]]; then
		label="${imagefilename}"
	else
		label=""
	fi
	dd if=/dev/zero of="${output}" iflag=fullblock bs=1M count=${imagesize}
	sync
	devices=$(losetup)
	for (( i=0; i<500; i++ )); do
		check=$(echo "${devices}" | grep "/dev/loop${i}")
		if [ "${check}" == "" ]; then
			loop="loop${i}"
			break
		fi
	done
	losetup "${loop}" "${output}"
	sync
	countdown=0
	while [ ! -e "/dev/${loop}" ]; do
		echo "/dev/${loop} not found, waiting for possible sync"
		if [ "${countdown}" == 2 ]; then
			echo "Loopback device setup failed!"
			exit
		fi
		sync
		sleep 5
		countdown=$(("${countdown}" + 1))
	done

	echo "Installing Ventoy to ${loop}..."
	read -p "Enter y to both prompts. Press enter to continue" temp
	bash "${ventoy}" -i "/dev/${loop}" -I -g -L "${label}"
	if [ ! -d usb ]; then
		mkdir usb
	else
		read -p "usb dir exists, delete and continue?: [y/N] " prompt
		if [ "${prompt}" == "y" ]; then
			rm -R usb
			mkdir usb
		else
			exit
		fi
	fi
	mount "/dev/${loop}p1" usb
	echo "Copying ${1} to disk image..."
	cp "${1}" usb/
	sync
	umount "/dev/${loop}p1"
	rm -R usb
	losetup -D "/dev/${loop}"
	chown "${currentuser}":"${currentuser}" "${output}"
	echo ""
	echo "Ventoy version: ${version}"
	echo "Source: ${1}"
	echo "Output: ${output}"
	echo "Label: ${label}"
fi
```

These are the steps
1) Get the size of the iso image and add 256
2) Create a blank disk image of that size
3) Check for available loopback device and map the disk image to it
4) Install Ventoy to the loopback device
5) Mount the exfat partition to usb folder
6) Copy the iso to the mounted partition
7) Unmount the partition
8) Unmount the loopback device
9) Copy new disk image to phone

I do not know how to create disk images in Windows, but I'm sure it's possible. What I don't know is if Ventoy will be able to install to it. The GUI on Linux would not show loopback devices.

I downloaded Windows like 4 times before realizing the usb driver wasn't there, not my sata drivers. I'm using UUP for windows iso's, so I thought I was misconfiguring something. After doing the above, Windows boots perfect.

Thank you for this program, I hate that DriveDroid development stopped, I used it all the time but it no longer works. I wish we had an application GUI for this, maybe I'll look into doing that but I have no idea how to request root access. Thanks again!

**Comment by nitanmarcel** [comment]
It should be self explanatory that you have to create the partition on the computer since you can't do it on the phone:)

**Comment by liwa-dev** [comment]
Hello, I'm facing a problem with this script. Initially, it asks me for the Ventoy path. I've downloaded it and placed it in /sdcard/download/Ventoy/install. Then, I ran the script again, and it solved a small issue. However, now I'm encountering another problem:

'~ $ sudo bash /sdcard/download/script.sh isofile
Source: isofile
Output: isofile.img

Please choose a partition label
1) Generated label from iso label: isofile
2) Generated label from file name: ISOFILEIMG

Choose 1, 2 or type a custom partition label (max 11 characters): 1
Set label to: isofile

Creating disk image...
ls: cannot access 'isofile': No such file or directory
/sdcard/download/script.sh: line 50: ( / 1000) + 64: syntax error: operand expected (error token is "/ 1000) + 64")
~ $'

I'm not sure what to do next. Please help, and thank you.



EDIT : i didn't know to place win 11 file in the [ISO File] location. I did that and it worked for me, but now I'm facing another problem help:
~ $ sudo bash /sdcard/download/script.sh /sdcard/download/win11.iso
win11.img already exists, overwrite?: [y/N] y
Source: /sdcard/download/win11.iso
Output: win11.img

Please choose a partition label
1) Generated label from iso label:      /SDCARD/DOW
2) Generated label from file name:      WIN11IMG

Choose 1, 2 or type a custom partition label (max 11 characters): 1
Set label to: /SDCARD/DOW

Creating disk image...
5760+0 records in
5760+0 records out
6039797760 bytes (6.0 GB, 5.6 GiB) copied, 21.3959 s, 282 MB/s
losetup: win11.img: failed to set up loop device: Device or resource busy
Installing Ventoy...
Say y to both questions

**********************************************
      Ventoy:   aarch64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Don't run Ventoy2Disk.sh here, please download the released install package, and run the script in it.
mount: '/dev/loop0p1'->'usb': No such file or directory
Copying /sdcard/download/win11.iso to disk image...
umount: /dev/loop0p1: No such file or directory
Finished.
Source: /sdcard/download/win11.iso
Final: win11.img
Partition Label: /SDCARD/DOW
~ $

**Comment by knuxyl** [comment]
Edit: I just realized you may be using terminal on your android phone to do this, if so I can't help any further. You need to do this on a Linux PC. It would be great to have this work on the phone itself, but I haven't tested it. I'll look into it but I doubt it'll work.

Edit2: I went to try this using Termux and it cannot work. Termux package manager installs bash for the user, and the user cannot access home directory in the way in which is needed by the script, even with sudo (at least on Android 13, which all my devices are running). By switching to su, bash functionality is lost and only sh is available to run scripts, which I know for a fact has some compatibility issues with bash scripts. I cannot even test using this on android due to these issues so this won't be supported.

This script creates a img file that can be used with isodrive. It doesn't interact whatsoever with isodrive. The script needs to be ran on a Linux PC.

Two problems
1) losetup: win11.img: failed to set up loop device: Device or resource busy
2) Don't run Ventoy2Disk.sh here, please download the released install package, and run the script in it.

Solutions
1) Please share the output of this command

ls -la /dev/ | grep loop

The loopback device is not being setup correctly. The code to find an available loopback device is very simple, so I'm thinking either you have a broken linux install somehow or there is a long wait. I've updated the script and added some syncs and a wait period. I have not tested this script or Ventoy on an arm64 system and I don't have any up and running to test.

2) Ventoy is complaining it cannot run due to not being a released version. This could be an incorrect error and it's just failing because the loopback device is not setup, or considering you had to have built this from source for it to say this or it's a beta, something went wrong in building it. Maybe a release flag needs to be set or something. I suggest downloading the release version for linux, the script itself in the release seems to support aarch64, as noted by this part in the script

if uname -m | grep -E -q 'aarch64|arm64'; then
    export TOOLDIR=aarch64

Please try again with the release version of Ventoy. https://github.com/ventoy/Ventoy/releases/download/v1.0.95/ventoy-1.0.95-linux.tar.gz

I have also updated the script in the initial post to fix some issues I found and be a little more verbose. I also added some wait time for the loopback device, there may be a delay creating it due to using an sd card for the OS (if ur using a SBC like raspberry  pi).

**Comment by Koladweep** [comment]
> I read the Wiki and saying to create a 10gb partition is a little vague. You cant repartition android, so I'm not quite sure what this means.
> 
> I found a better solution though. The linux file gadget driver isn't included in Windows which is why it complains drivers are missing. It boots the live environment, but does not mount the actual installer sources to a letter because it doesn't load the driver.
> 
> The basic idea is to create a dummy USB image, install ventoy on it, and then copy the Windows iso over. I'm guessing loading the installer through Ventoy is like a virtual environment, so Windows doesn't communicate directly with the hardware/usb it is on.
> 
> Ventoy: https://github.com/ventoy/Ventoy
> 
> This is the bash script I wrote to do this in Linux
> 
> usage sudo bash script.sh ISOFILE
> 
> ```
> #!/bin/bash
> ventoy="ventoy/Ventoy2Disk.sh"
> if [ "$(whoami)" != "root" ]; then
> 	echo "Please run this as root or sudo"
> 	exit
> fi
> user="${SUDO_USER}"
> if [ "${user}" == "" ]; then
> 	user="root"
> fi
> if [ ! -f "${ventoy}" ]; then
> 	echo "Please update ventoy location in this script or move ventoy to"
> 	echo "ventoy/"
> 	echo "inside this directory"
> 	echo "Ventory download here"
> 	echo "https://www.ventoy.net/en/download.html"
> fi
> if [ "${1}" != "" ]; then
> 	fname="$(basename "${1%.*}").img"
> 	if [ "${fname}" == "${1}" ]; then
> 		fname="$(basename "${1}")_new.img"
> 	fi
> 	if [ -f "${fname}" ]; then
> 		read -p "${fname} already exists, overwrite?: [y/N] " prompt
> 		if [ "${prompt}" == "y" ]; then
> 			rm -R "${fname}"
> 		else
> 			exit
> 		fi
> 	fi
> 	echo "Source: ${1}"
> 	echo "Output: ${fname}"
> 	echo ""
> 	echo "Please choose a partition label"
> 	label="$(file "${1}" | cut -f 2 -d "'" | tr [:lower:] [:upper:])"
> 	flabel="$(basename ${fname} | sed 's/\.//g' | sed 's/-//g' | sed 's/_//g' | tr [:lower:] [:upper:])"
> 	echo -e "1) Generated label from iso label:\t${label:0:11}"
> 	echo -e "2) Generated label from file name:\t${flabel:0:11}"
> 	echo ""
> 	read -p "Choose 1, 2 or type a custom partition label (max 11 characters): " l
> 	if [ "${l}" == "1" ]; then
> 		label="${label:0:11}"
> 	elif [ "${l}" == "2" ]; then
> 		label="${fname:0:11}"
> 	else
> 		l=$(echo "${l}" | tr [:lower:] [:upper:])
> 		label="${l:0:11}"
> 	fi
> 	echo "Set label to: ${label}"
> 	echo ""
> 	echo "Creating disk image..."
> 	fsize=$((($(ls -s "${1}" | cut -f 1 -d " ") / 1000) + 64))
> 	dd if=/dev/zero of="${fname}" iflag=fullblock bs=1M count=${fsize}
> 	sync
> 	devices=$(losetup)
> 	for (( i=0; i<500; i++ )); do
> 		check=$(echo "${devices}" | grep "/dev/loop${i}")
> 		if [ "${check}" == "" ]; then
> 			loop="loop${i}"
> 			break
> 		fi
> 	done
> 	losetup "${loop}" "${fname}"
> 	sync
> 	countdown=0
> 	while [ ! -e "/dev/${loop}" ]; do
> 		echo "/dev/${loop} not found, waiting for possible sync"
> 		if [ "${countdown}" == 2 ]; then
> 			break
> 		fi
> 		sync
> 		sleep 5
> 		countdown=$(("${countdown}" + 1))
> 	done
> 	if [ ! -e "/dev/${loop}" ]; then
> 		echo "losetup failed. /dev/${loop} was not created"
> 		exit
> 	fi
> 	echo "Installing Ventoy to ${loop}..."
> 	echo "Say y to both questions"
> 	bash "${ventoy}" -i "/dev/${loop}" -I -g -L "${label}"
> 	if [ ! -d usb ]; then
> 		mkdir usb
> 	else
> 		read -p "usb dir exists, delete and continue?: [y/N] " prompt
> 		if [ "${prompt}" == "y" ]; then
> 			rm -R usb
> 			mkdir usb
> 		else
> 			exit
> 		fi
> 	fi
> 	mount "/dev/${loop}p1" usb
> 	echo "Copying ${1} to disk image..."
> 	cp "${1}" usb/
> 	sync
> 	umount "/dev/${loop}p1"
> 	rm -R usb
> 	losetup -D "/dev/${loop}"
> 	chown "${user}":"${user}" "${fname}"
> 	echo "Finished."
> 	echo "Source: ${1}"
> 	echo "Final: ${fname}"
> 	echo "Partition Label: ${label}"
> else
> 	echo "Usage:"
> 	echo "isodrive.sh ISOFILE"
> 	echo "IMAGEFILE = your source iso file"
> fi
> ```
> 
> These are the steps
> 
>     1. Get the size of the iso image and add 256
> 
>     2. Create a blank disk image of that size
> 
>     3. Check for available loopback device and map the disk image to it
> 
>     4. Install Ventoy to the loopback device
> 
>     5. Mount the exfat partition to usb folder
> 
>     6. Copy the iso to the mounted partition
> 
>     7. Unmount the partition
> 
>     8. Unmount the loopback device
> 
>     9. Copy new disk image to phone
> 
> 
> I do not know how to create disk images in Windows, but I'm sure it's possible. What I don't know is if Ventoy will be able to install to it. The GUI on Linux would not show loopback devices.
> 
> I downloaded Windows like 4 times before realizing the usb driver wasn't there, not my sata drivers. I'm using UUP for windows iso's, so I thought I was misconfiguring something. After doing the above, Windows boots perfect.
> 
> Thank you for this program, I hate that DriveDroid development stopped, I used it all the time but it no longer works. I wish we had an application GUI for this, maybe I'll look into doing that but I have no idea how to request root access. Thanks again!

I am so grateful this was solved.

**Comment by nitanmarcel** [comment]
For some reason my laptop refused to display the boot option with the generated image.

**Comment by dhuux** [comment]
changed couple of lines in Ventoy script to the right path and also in this script. losetup complained node `/dev/loop0` missing so i created it.  now it sounds like it would work if say yes. not sure though. there is only 5GB left of my device. it would probably run out of space before finishing.  but is there any danger to this since this is a phone not a computer?
and what is `/dev/block/loop0` in my chroot exactly? what is on it that i will lose?

the phone is very old. j4+.

![Screenshot_20240829-151447_Termux_Monet](https://github.com/user-attachments/assets/094dc01f-c2ee-4915-9f4c-7701fa24e5f5)


thanks.

**Comment by dhuux** [comment]
@knuxyl  i struggled to free some space and this is how it ended up. was it supposed to look like this? and why this `invalid group` error? i have no scripting knowledge to make it right though.

![Screenshot_20240829-195531_Termux_Monet](https://github.com/user-attachments/assets/e9eb9e23-9ad8-4fa8-9811-5c81c3b2d1ff)


![Screenshot_20240829-200306_MiXplorer](https://github.com/user-attachments/assets/368fd985-90a6-476a-9bc0-57aa0b0acc5b)

**Comment by knuxyl** [comment]
@dhuux I talked with someone else earlier in this post and I came to the conclusion this wouldn't work on Android but looking at your output it would seem like it did. chown isn't working and I don't think that will be a problem because isodrive requires root access anyways. That line just changes the ownership of the image file to the current user so you can do what you want with it. You may have to sudo rm imagefile.iso if you want to delete it though. I'm suprised this worked at all on your phone. I don't see output of ventoy if it installed correctly or not.

This is not the most compatible nor optimized script, probably just a good starting point. There are much easier ways to accomplish this on Linux, such as using gnome-disks to create the blank image and mounting it, then installing ventoy on it. I have no idea why I decided to do this the hard way when I created this. But it seems like some phones will work with this so I guess that's a bonus. You should test it to see if it works, I really can't tell you much from a screenshot.

**Comment by dhuux** [comment]
@knuxyl  well, you told them that it wouldn't work in a plain Termux env and i guess it's true cause Termux doesn't provide mkexfats tool which Ventoy needs i think and there could be other problems. but in a chrooted Linux distro I'm using Arch btw), `Ventoy` will work no matter the phone or which android version you are on. you will just need to create or in Ventoy script correct the path to were your device nodes are and they are under here `/dev/block/` not `/dev/`. 

if you make Ventoy work and create `/dev/loop0` for `losetup`, then there is no reason this script wouldn't work i guess.


![Screenshot_20240901-183558_Termux_Monet](https://github.com/user-attachments/assets/38ded65c-4d01-4e8b-b86f-6498e7af7f3a)

chown works after replacing the line with `"${USER:=$(/usr/bin/id -run)}:$USER"` which i copied from somewhere in the internet. 

forgive me for my newbie vocabs.
thanks for the script.
