### ISSUE TITLE
RW mode does not work

### ISSUE THREAD

**Issue by knuxyl** [nitanmarcel/isodrive-magisk#3]
Using a partitioned .img file created on Linux and mounting with
`isodrive IMAGE.img -rw`
does not give me write access, only read.

The ouput of the command is
```
Write:   -> /config/usb_gadget/g1/IDC
Write: IMAGE.img -> /config/usb_gadget/g1/functions/mass_storage.0/lun.0/file
Write: -rw -> /config/usb_gadget/g1/functions/mass_storage.0/lun.0/cdrom
Write: 0 -> /config/usb_gadget/g1/functions/mass_Storage.0/lun.0/ro
Write: a600000.dwc3 -> /config/usb_gadget/g1/UDC
```

When I cat ro and cdrom I get this
```
cat /config/usb_gadget/g1/functions/mass_storage.0/lun.0/ro
1
cat /config/usb_gadget/g1/functions/mass_storage.0/lun.0/cdrom
0
```

dmesg on Debian gives me this about the usb
```
[ 4309.035017] sd 10:0:0:0: [sdj] Write Protect is on
[ 4309.035020] sd 10:0:0:0: [sdj] Mode Sense: 0f 00 80 00
[ 4309.035677] sd 10:0:0:0: [sdj] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[ 4309.049355]  sdj: sdj1 sdj2
[ 4309.049704] sd 10:0:0:0: [sdj] Attached SCSI removable disk
```

Device: Google Pixel 5
Android13: Lineageos 20-20230705-NIGHTLY-redfin
Magisk: 26.1

**Comment by nitanmarcel** [comment]
> Using a partitioned .img file created on Linux and mounting with `isodrive IMAGE.img -rw` does not give me write access, only read.
> 
> The ouput of the command is
> 
> ```
> Write:   -> /config/usb_gadget/g1/IDC
> Write: IMAGE.img -> /config/usb_gadget/g1/functions/mass_storage.0/lun.0/file
> Write: -rw -> /config/usb_gadget/g1/functions/mass_storage.0/lun.0/cdrom
> Write: 0 -> /config/usb_gadget/g1/functions/mass_Storage.0/lun.0/ro
> Write: a600000.dwc3 -> /config/usb_gadget/g1/UDC
> ```
> 
> When I cat ro and cdrom I get this
> 
> ```
> cat /config/usb_gadget/g1/functions/mass_storage.0/lun.0/ro
> 1
> cat /config/usb_gadget/g1/functions/mass_storage.0/lun.0/cdrom
> 0
> ```
> 
> dmesg on Debian gives me this about the usb
> 
> ```
> [ 4309.035017] sd 10:0:0:0: [sdj] Write Protect is on
> [ 4309.035020] sd 10:0:0:0: [sdj] Mode Sense: 0f 00 80 00
> [ 4309.035677] sd 10:0:0:0: [sdj] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
> [ 4309.049355]  sdj: sdj1 sdj2
> [ 4309.049704] sd 10:0:0:0: [sdj] Attached SCSI removable disk
> ```
> 
> Device: Google Pixel 5 Android13: Lineageos 20-20230705-NIGHTLY-redfin Magisk: 26.1

Are you using the latest version? The parsing of the arguments is also wrong

**Comment by nitanmarcel** [comment]
https://github.com/nitanmarcel/isodrive-magisk/releases/download/v2.0/isodrive-magisk-v2.0.zip

**Comment by knuxyl** [comment]
I found out I was using 1.1, so I just installed the one you linked and I still have the same problem, the drive is not writeable. 
The app says usage is isodrive FILE OPTIONS so I did
isodrive IMAGE.img -rw
but putting -rw before IMAGE.img doesn't seem to make a difference, and the loop on the arguments in the source would make the order not matter, right?

Version 2.0 is writing 0 to both cdrom and ro, regardless of the order I pass the arguments. But when I cat both of them, cdrom is 0 and ro is 1.

Dmesg reports write protected on, and trying to sudo touch a file says read-only file system.

**Comment by knuxyl** [comment]
I just reran the command after unplugging and plugging back in and now write protect is off and it says that ro is now 0. Write is now also working. I guess I can't remount the image while still connected to PC, that's all I did differently. Thanks!

**Comment by knuxyl** [comment]
I just reran the command after unplugging and plugging back in and now write protect is off and it says that ro is now 0. Write is now also working. I guess I can't remount the image while still connected to PC, that's all I did differently. Thanks!

**Comment by knuxyl** [comment]
Now I can't seem to get it to work again. I don't know what is going on. I tried manually echo 0 into cdrom and ro, i tried different combos of unplugged/plugged when running commands, etc.

**Comment by knuxyl** [comment]
Now I can't seem to get it to work again. I don't know what is going on. I tried manually echo 0 into cdrom and ro, i tried different combos of unplugged/plugged when running commands, etc.

I'm going to have to get back to testing tomorrow, I did everything I could to get it to work but it only worked once. I have multiple image files as well that I've tested to make sure I didn't corrupt the one that was mounted once as rw.

**Comment by nitanmarcel** [comment]
You can't have CDROM and RW together.

**Comment by knuxyl** [comment]
Yes I know. I have not been using them together. I have been sharing what values the app writes to cdrom and ro and what values are actually there. I have only been using -rw.

**Comment by nitanmarcel** [comment]
Please test 2.1 :)

https://github.com/nitanmarcel/isodrive-magisk/releases/tag/v2.1

**Comment by knuxyl** [comment]
Yep that fixed it! I guess putting image into file after the ro and cdrom was the trick? Thanks!

**Comment by nitanmarcel** [comment]
> Yep that fixed it! I guess putting image into file after the ro and cdrom was the trick? Thanks!

Yes, as specified in a PR on the isodrive repo which I totally forgot about xD
