### ISSUE TITLE
How to save sessions? (persistent boot)

### ISSUE THREAD

**Issue by vjaykrsna** [nitanmarcel/isodrive-magisk#4]
First of all thanks for this wonderful project. I think this is so cool and I was looking for something like this for a long time.
I am wondering if it is possible to save my data so then when i reboot it doesn't start from fresh boot again.
maybe we can create a data partition too like /home or something. or maybe integrate data persistance within the iso.

**Comment by nitanmarcel** [comment]
You can modify the zip archive to run a service at boot that automatically run a command, in this case an isodrive command at boot

https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md#shell-scripts-sh

**Comment by nitanmarcel** [comment]
Oh, I misunderstood the question. Update to the latest version from the releases page. It should have a fix for mounting the iso as rw.

About creating a fully bootable environment consult https://github.com/nitanmarcel/isodrive/wiki/Convert-an-OS-into-a-bootable-environment
